// ============================================================
// UFOlogist — Curated case database
// ~100 well-documented cases (1942–2024), each with original
// source links. Types follow an extended Hynek classification.
// cred: evidence rating 1–5 (5 = radar + multiple trained
// witnesses + official documentation)
// ============================================================

const TYPE_META = {
  NL:   { label: 'Luces nocturnas',      color: '#ffd166', desc: 'Luces anómalas observadas de noche (Hynek: Nocturnal Lights).' },
  DD:   { label: 'Disco diurno',          color: '#8ecae6', desc: 'Objeto observado a plena luz del día (Hynek: Daylight Discs).' },
  RV:   { label: 'Radar-Visual',          color: '#b388ff', desc: 'Detección simultánea por radar y testigos visuales. La categoría con mayor valor probatorio.' },
  CE1:  { label: 'Encuentro cercano I',   color: '#80ed99', desc: 'Objeto a menos de ~150 m, sin interacción con el entorno.' },
  CE2:  { label: 'Encuentro cercano II',  color: '#57cc99', desc: 'Evidencia física: huellas, quemaduras, interferencias electromagnéticas, efectos fisiológicos.' },
  CE3:  { label: 'Encuentro cercano III', color: '#38a3a5', desc: 'Observación de presuntos ocupantes o entidades asociadas al objeto.' },
  CE4:  { label: 'Encuentro cercano IV',  color: '#22577a', desc: 'Presunta abducción o interacción directa reportada por el testigo.' },
  MIL:  { label: 'Militar / Aviación',    color: '#ef476f', desc: 'Incidentes con pilotos, bases o sistemas de defensa. Suelen incluir documentación oficial.' },
  USO:  { label: 'USO / Transmedio',      color: '#118ab2', desc: 'Objetos sumergidos no identificados o con comportamiento transmedio (aire-agua).' },
  MASS: { label: 'Avistamiento masivo',   color: '#f78c6b', desc: 'Cientos o miles de testigos independientes del mismo evento.' },
};

const CASES = [
// ------------------------------ 1940s ------------------------------
{ id:'battle-la-1942', name:'Batalla de Los Ángeles', date:'1942-02-25', lat:34.05, lng:-118.24, loc:'Los Ángeles, California', country:'EE.UU.', type:'MIL', cred:4,
  summary:'La artillería antiaérea disparó más de 1.400 proyectiles contra un objeto lento e iluminado por reflectores sobre la ciudad, semanas después de Pearl Harbor. El secretario de Marina lo atribuyó a "nervios de guerra"; el Ejército mantuvo que hubo un objeto real.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Battle_of_Los_Angeles'],['Foto LA Times 1942','https://www.latimes.com/local/lanow/la-me-ln-battle-la-photo-20110310-story.html']] },
{ id:'foo-fighters-1944', name:'Foo Fighters (frente europeo)', date:'1944-11-23', lat:48.58, lng:7.75, loc:'Valle del Rin, Alsacia', country:'Francia/Alemania', type:'MIL', cred:4,
  summary:'Tripulaciones aliadas del escuadrón nocturno 415th reportaron repetidamente bolas de luz que perseguían y maniobraban alrededor de sus aviones. Documentado en partes oficiales de misión; nunca se explicó satisfactoriamente.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Foo_fighter']] },
{ id:'ghost-rockets-1946', name:'Cohetes fantasma escandinavos', date:'1946-07-09', lat:66.05, lng:22.05, loc:'Lago Kölmjärv, Norrbotten', country:'Suecia', type:'DD', cred:3,
  summary:'Unos 2.000 reportes de objetos tipo cohete sobre Escandinavia. El ejército sueco dragó lagos sin hallar restos; documentos desclasificados muestran preocupación de EE.UU. y Reino Unido.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Ghost_rockets']] },
{ id:'kenneth-arnold-1947', name:'Kenneth Arnold — Mt. Rainier', date:'1947-06-24', lat:46.85, lng:-121.76, loc:'Monte Rainier, Washington', country:'EE.UU.', type:'DD', cred:3,
  summary:'El piloto privado Kenneth Arnold observó nueve objetos en formación volando "como platillos rebotando en el agua" a velocidad estimada de 1.900 km/h. Origen del término "flying saucer" y del fenómeno moderno.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Kenneth_Arnold_UFO_sighting'],['Informe Project Blue Book (NARA)','https://www.archives.gov/research/military/air-force/ufos']] },
{ id:'roswell-1947', name:'Incidente de Roswell', date:'1947-07-08', lat:33.95, lng:-105.31, loc:'Rancho Foster, cerca de Corona, Nuevo México', country:'EE.UU.', type:'CE2', cred:3,
  summary:'El 509th Bomb Group anunció oficialmente la recuperación de un "disco volador"; horas después la versión cambió a globo meteorológico. En 1994 la USAF lo vinculó al Proyecto Mogul. Caso central de la mitología del crash-retrieval.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Roswell_incident'],['Informe USAF 1994 (GPO)','https://www.govinfo.gov/app/details/GOVPUB-D301-PURL-LPS112883']] },
{ id:'mantell-1948', name:'Incidente Mantell', date:'1948-01-07', lat:37.0, lng:-85.91, loc:'Franklin, Kentucky', country:'EE.UU.', type:'MIL', cred:4,
  summary:'El capitán Thomas Mantell murió al estrellarse su P-51 mientras perseguía un objeto enorme y metálico reportado por la torre de Godman Field. Explicación más aceptada: globo Skyhook secreto; el caso impulsó la investigación oficial.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Mantell_UFO_incident']] },
{ id:'chiles-whitted-1948', name:'Chiles–Whitted (Eastern Airlines)', date:'1948-07-24', lat:32.0, lng:-87.0, loc:'Cerca de Montgomery, Alabama', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Dos pilotos comerciales veteranos vieron un objeto tubular con "ventanillas" iluminadas pasar a escasos metros de su DC-3. El caso motivó el "Estimate of the Situation" del Proyecto Sign, que concluía origen interplanetario y fue rechazado por el general Vandenberg.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Chiles-Whitted_UFO_encounter'],['NICAP','http://www.nicap.org/480724montgomery_dir.htm']] },
{ id:'gorman-1948', name:'Dogfight de Gorman', date:'1948-10-01', lat:46.88, lng:-96.79, loc:'Fargo, Dakota del Norte', country:'EE.UU.', type:'MIL', cred:3,
  summary:'El piloto de la Guardia Nacional George Gorman mantuvo 27 minutos de persecución aérea con una luz pequeña y extremadamente maniobrable, confirmada por la torre. Blue Book lo cerró como "globo iluminado".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Gorman_dogfight']] },

// ------------------------------ 1950s ------------------------------
{ id:'mcminnville-1950', name:'Fotografías de McMinnville', date:'1950-05-11', lat:45.21, lng:-123.2, loc:'McMinnville, Oregón', country:'EE.UU.', type:'DD', cred:3,
  summary:'Paul y Evelyn Trent fotografiaron dos veces un disco metálico sobre su granja. El Informe Condon (1968) lo calificó entre los pocos casos donde "todos los factores investigados son consistentes con un objeto real, metálico y artificial".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/McMinnville_UFO_photographs']] },
{ id:'mariana-1950', name:'Película de Mariana', date:'1950-08-15', lat:47.5, lng:-111.3, loc:'Great Falls, Montana', country:'EE.UU.', type:'DD', cred:3,
  summary:'Nick Mariana filmó dos objetos brillantes y discoidales en pleno día: una de las primeras películas de OVNIs analizadas por la USAF. El análisis oficial no logró identificarlos de forma concluyente.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Mariana_UFO_incident']] },
{ id:'lubbock-1951', name:'Luces de Lubbock', date:'1951-08-25', lat:33.58, lng:-101.85, loc:'Lubbock, Texas', country:'EE.UU.', type:'NL', cred:3,
  summary:'Formaciones en V de luces azul-verdosas vistas por profesores universitarios de ciencias y fotografiadas por Carl Hart Jr. Blue Book nunca explicó las fotos de manera definitiva.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Lubbock_Lights']] },
{ id:'tremonton-1952', name:'Película de Tremonton', date:'1952-07-02', lat:41.71, lng:-112.17, loc:'Tremonton, Utah', country:'EE.UU.', type:'DD', cred:3,
  summary:'El suboficial de Marina Delbert Newhouse filmó ~12 objetos brillantes maniobrando. Analizada fotograma a fotograma por la Marina, que descartó aves y aviones; el Panel Robertson la reabrió como "probables gaviotas".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/1952_Tremonton_UFO_film']] },
{ id:'washington-1952', name:'Oleada de Washington D.C.', date:'1952-07-19', lat:38.91, lng:-77.04, loc:'Washington D.C.', country:'EE.UU.', type:'RV', cred:5,
  summary:'Durante dos fines de semana, múltiples retornos de radar en el Aeropuerto Nacional y Andrews AFB coincidieron con luces visibles y cazas F-94 que no lograron interceptarlas. Provocó la mayor rueda de prensa del Pentágono desde la 2ª Guerra Mundial y el Panel Robertson de la CIA.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/1952_Washington,_D.C._UFO_incident'],['NICAP','http://www.nicap.org/washington_sightings_52.htm']] },
{ id:'flatwoods-1952', name:'Monstruo de Flatwoods', date:'1952-09-12', lat:38.72, lng:-80.65, loc:'Flatwoods, Virginia Occidental', country:'EE.UU.', type:'CE3', cred:2,
  summary:'Tras ver descender un objeto brillante, un grupo de vecinos reportó una figura alta con "cabeza de pica" y olor metálico irritante. Explicaciones propuestas: meteoro brillante más una lechuza; los testigos sufrieron síntomas físicos reales.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Flatwoods_monster']] },
{ id:'kinross-1953', name:'Desaparición Kinross (Moncla)', date:'1953-11-23', lat:47.0, lng:-85.5, loc:'Lago Superior, Michigan', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Un F-89 Scorpion enviado a interceptar un blanco de radar no identificado se fundió con el eco en pantalla y desapareció con sus dos tripulantes. Ni el avión ni los cuerpos fueron recuperados. La USAF lo atribuyó a un avión canadiense, versión que Canadá negó.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Felix_Moncla']] },
{ id:'quarouble-1954', name:'Quarouble (Marius Dewilde)', date:'1954-09-10', lat:50.41, lng:3.6, loc:'Quarouble, Norte', country:'Francia', type:'CE3', cred:2,
  summary:'Caso emblemático de la gran oleada francesa de 1954: un obrero reportó dos pequeñas entidades junto a un objeto sobre las vías; la gendarmería documentó marcas de presión de varias toneladas en las traviesas.',
  sources:[['Wikipedia (FR)','https://fr.wikipedia.org/wiki/Affaire_de_Quarouble']] },
{ id:'florence-1954', name:'Estadio de Florencia', date:'1954-10-27', lat:43.77, lng:11.26, loc:'Florencia, Toscana', country:'Italia', type:'MASS', cred:3,
  summary:'Un partido Fiorentina–Pistoiese se detuvo cuando 10.000 espectadores observaron objetos lentos sobre el estadio, acompañados de filamentos ("cabello de ángel") que caían del cielo. Cubierto por la BBC en su 60º aniversario.',
  sources:[['BBC News','https://www.bbc.com/news/magazine-29342407'],['Wikipedia','https://en.wikipedia.org/wiki/1954_Tuscany_UFO_sightings']] },
{ id:'kelly-1955', name:'Kelly–Hopkinsville', date:'1955-08-21', lat:36.86, lng:-87.48, loc:'Kelly, Kentucky', country:'EE.UU.', type:'CE3', cred:2,
  summary:'Dos familias dispararon durante horas contra pequeñas entidades plateadas de ojos grandes que se asomaban a la granja. La policía encontró a los testigos en pánico genuino; origen del arquetipo "little green men".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Kelly%E2%80%93Hopkinsville_encounter']] },
{ id:'lakenheath-1956', name:'Lakenheath–Bentwaters', date:'1956-08-13', lat:52.41, lng:0.56, loc:'RAF Lakenheath, Suffolk', country:'Reino Unido', type:'RV', cred:5,
  summary:'Objetos rastreados simultáneamente por radares de tierra de dos bases, radar aéreo y testigos visuales; un Venom de la RAF fue burlado repetidamente por el objeto, que se le situó a cola. El Informe Condon admitió que "la probabilidad de un auténtico OVNI parece bastante alta".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Lakenheath-Bentwaters_radar/visual_UFO_incident'],['NICAP','http://www.nicap.org/560813lakenheath_dir.htm']] },
{ id:'rb47-1957', name:'Incidente del RB-47', date:'1957-07-17', lat:32.0, lng:-91.5, loc:'Entre Mississippi y Texas (Golfo)', country:'EE.UU.', type:'RV', cred:5,
  summary:'Un RB-47 de guerra electrónica fue seguido durante 1,5 h y 1.100 km por un objeto detectado por radar de a bordo, equipos ELINT, radares de tierra y visualmente. Uno de los casos con instrumentación múltiple mejor documentados de la historia.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/1957_RB-47_UFO_encounter'],['NICAP','http://www.nicap.org/570717gulf_dir.htm']] },
{ id:'vilas-boas-1957', name:'Antônio Vilas Boas', date:'1957-10-16', lat:-19.86, lng:-49.77, loc:'São Francisco de Sales, Minas Gerais', country:'Brasil', type:'CE4', cred:2,
  summary:'Primer caso de abducción ampliamente documentado: un joven agricultor relató ser llevado a bordo de un objeto mientras araba de noche. Examinado por el médico Olavo Fontes, que registró lesiones compatibles con radiación.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Ant%C3%B4nio_Vilas-Boas']] },
{ id:'levelland-1957', name:'Levelland', date:'1957-11-02', lat:33.59, lng:-102.38, loc:'Levelland, Texas', country:'EE.UU.', type:'CE2', cred:4,
  summary:'En una noche, al menos 15 testigos independientes en distintas carreteras reportaron un objeto luminoso que apagaba motores y faros de sus vehículos, restaurándose al alejarse. Caso clásico de efectos electromagnéticos; Blue Book lo despachó como "rayo en bola" con una investigación de horas.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Levelland_UFO_case'],['NICAP','http://www.nicap.org/571102levelland_dir.htm']] },
{ id:'trindade-1958', name:'Isla Trindade', date:'1958-01-16', lat:-20.51, lng:-29.31, loc:'Isla Trindade, Atlántico Sur', country:'Brasil', type:'DD', cred:3,
  summary:'Desde el buque escuela Almirante Saldanha, el fotógrafo Almiro Baraúna captó cuatro imágenes de un objeto anular tipo "Saturno" ante decenas de tripulantes de la Marina brasileña. Las fotos fueron analizadas y avaladas por la Marina; el debate sobre su autenticidad sigue abierto.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Trindade_Island_UFO_incident']] },
{ id:'gill-1959', name:'Padre William Gill — Boianai', date:'1959-06-26', lat:-10.32, lng:150.35, loc:'Boianai, Papúa', country:'Papúa Nueva Guinea', type:'CE3', cred:3,
  summary:'El misionero anglicano William Gill y 37 testigos observaron durante dos noches un objeto con figuras humanoides en su parte superior que respondieron a sus saludos. Hynek lo consideró uno de los casos CE3 más sólidos por el número y calidad de los testigos.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Father_Gill_sighting']] },

// ------------------------------ 1960s ------------------------------
{ id:'red-bluff-1960', name:'Red Bluff (patrulla CHP)', date:'1960-08-13', lat:40.18, lng:-122.24, loc:'Red Bluff, California', country:'EE.UU.', type:'NL', cred:3,
  summary:'Dos agentes de la patrulla de carreteras persiguieron un objeto luminoso que ascendía y descendía con movimientos imposibles, confirmado por otros agentes y por radar local según el parte. Caso clásico de testigos policiales.',
  sources:[['NICAP','http://www.nicap.org/600813redbluff_dir.htm']] },
{ id:'hill-1961', name:'Abducción de Betty y Barney Hill', date:'1961-09-19', lat:44.09, lng:-71.38, loc:'Lincoln, New Hampshire', country:'EE.UU.', type:'CE4', cred:2,
  summary:'El primer caso de abducción mediático de EE.UU.: el matrimonio Hill reportó pérdida de tiempo y, bajo hipnosis, un examen a bordo. El "mapa estelar" de Betty y el vestido analizado mantienen vivo el debate. Documentado por el proyecto Blue Book como caso independiente de observación.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Barney_and_Betty_Hill_incident']] },
{ id:'trancas-1963', name:'Caso Trancas', date:'1963-10-21', lat:-26.23, lng:-65.28, loc:'Trancas, Tucumán', country:'Argentina', type:'CE2', cred:2,
  summary:'La familia Moreno reportó seis objetos en formación junto a las vías del tren, con haces de luz, calor intenso y olor a azufre; se documentaron marcas en el terreno. Uno de los casos clásicos de la casuística argentina.',
  sources:[['Wikipedia (ES)','https://es.wikipedia.org/wiki/Caso_Trancas']] },
{ id:'socorro-1964', name:'Socorro (Lonnie Zamora)', date:'1964-04-24', lat:34.06, lng:-106.89, loc:'Socorro, Nuevo México', country:'EE.UU.', type:'CE3', cred:4,
  summary:'El policía Lonnie Zamora observó un objeto ovoide blanco con dos figuras pequeñas, que despegó con llama azul dejando huellas de tren de aterrizaje y matorrales quemados. El caso quedó como "no identificado" en Blue Book y Hynek lo consideró de los más creíbles del archivo.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Lonnie_Zamora_incident'],['NICAP','http://www.nicap.org/640424socorro_dir.htm']] },
{ id:'valensole-1965', name:'Valensole (Maurice Masse)', date:'1965-07-01', lat:43.84, lng:5.98, loc:'Valensole, Alpes de Alta Provenza', country:'Francia', type:'CE3', cred:3,
  summary:'Un agricultor de lavanda observó un objeto posado y dos pequeñas entidades que lo paralizaron con un dispositivo. La gendarmería verificó el suelo compactado y el lavandín no volvió a crecer en el punto durante años. Investigado por GEPAN.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Valensole_UFO_incident']] },
{ id:'exeter-1965', name:'Incidente de Exeter', date:'1965-09-03', lat:42.98, lng:-70.95, loc:'Exeter, New Hampshire', country:'EE.UU.', type:'CE1', cred:4,
  summary:'Un objeto con luces rojas pulsantes acosó a un joven y fue confirmado de cerca por dos policías. El Pentágono terminó admitiendo que el caso quedaba sin explicar. Origen del libro "Incident at Exeter" de John G. Fuller.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Exeter_incident']] },
{ id:'kecksburg-1965', name:'Kecksburg', date:'1965-12-09', lat:40.18, lng:-79.46, loc:'Kecksburg, Pensilvania', country:'EE.UU.', type:'CE2', cred:3,
  summary:'Una bola de fuego atravesó seis estados y algo cayó en un bosque de Pensilvania. Testigos describieron un objeto acampanado con marcas tipo jeroglífico y un amplio despliegue militar que acordonó la zona. La NASA atribuyó los restos a un satélite ruso, pero declaró perdidos los archivos del caso tras una demanda FOIA.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Kecksburg_UFO_incident']] },
{ id:'wanaque-1966', name:'Embalse de Wanaque', date:'1966-01-11', lat:41.05, lng:-74.3, loc:'Wanaque, Nueva Jersey', country:'EE.UU.', type:'NL', cred:2,
  summary:'Policías y vecinos de varios municipios reportaron durante semanas una luz brillante maniobrando sobre el embalse, con presunto haz que derretía el hielo. Caso clásico de oleada local con testigos oficiales.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Wanaque_Reservoir_UFO_sightings']] },
{ id:'dexter-1966', name:'Dexter/Hillsdale ("gas de pantano")', date:'1966-03-20', lat:42.34, lng:-83.89, loc:'Dexter, Míchigan', country:'EE.UU.', type:'CE1', cred:2,
  summary:'Decenas de testigos, incluidos policías, vieron luces sobre pantanos en Míchigan. La explicación de Hynek como "gas de pantano" provocó burla nacional, la indignación del congresista Gerald Ford y, finalmente, el encargo del Informe Condon. Punto de inflexión político del fenómeno.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/1966_Michigan_UFO_sightings']] },
{ id:'westall-1966', name:'Westall (colegio)', date:'1966-04-06', lat:-37.93, lng:145.13, loc:'Clayton South, Melbourne', country:'Australia', type:'MASS', cred:3,
  summary:'Más de 200 alumnos y profesores de dos colegios observaron un objeto plateado descender tras unos árboles y partir a gran velocidad, seguido por avionetas. Testigos relatan presencia militar posterior y consignas de silencio. El mayor avistamiento masivo escolar de Australia.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Westall_UFO_encounter']] },
{ id:'portage-1966', name:'Persecución del condado de Portage', date:'1966-04-17', lat:41.16, lng:-81.24, loc:'Condado de Portage, Ohio', country:'EE.UU.', type:'CE1', cred:3,
  summary:'Agentes de policía de Ohio persiguieron durante 137 km y media hora un objeto luminoso a baja altura hasta Pensilvania. Blue Book lo cerró como "satélite y Venus", explicación rechazada por escrito por los agentes y criticada por Hynek. Inspiró la escena de persecución de "Encuentros en la tercera fase".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Portage_County_UFO_chase']] },
{ id:'tully-1966', name:'Nidos de Tully', date:'1966-01-19', lat:-17.93, lng:145.93, loc:'Tully, Queensland', country:'Australia', type:'CE2', cred:2,
  summary:'Un agricultor vio un objeto elevarse de una laguna dejando un círculo de juncos aplastados en espiral: los célebres "saucer nests", precursores de los círculos de cosecha. Investigado por la RAAF.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Tully_%22saucer_nest%22']] },
{ id:'malmstrom-1967', name:'Malmstrom AFB — misiles desactivados', date:'1967-03-24', lat:47.5, lng:-111.18, loc:'Malmstrom AFB, Montana', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Según el oficial de lanzamiento Robert Salas y documentos desclasificados, diez misiles nucleares Minuteman quedaron fuera de servicio mientras el personal de seguridad reportaba un objeto brillante sobre la puerta de la instalación. Boeing no halló causa técnica concluyente. Pieza clave del expediente "OVNIs y armas nucleares".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Malmstrom_AFB_UFO_incident'],['CUFON — documentos','https://www.cufon.org/cufon/malmstrom/malm1.htm']] },
{ id:'falcon-lake-1967', name:'Falcon Lake (Stefan Michalak)', date:'1967-05-20', lat:50.76, lng:-95.27, loc:'Parque Whiteshell, Manitoba', country:'Canadá', type:'CE2', cred:3,
  summary:'Un prospector aficionado sufrió quemaduras en patrón de rejilla al tocar un objeto aterrizado que expulsó gas caliente. Hospitalizado con síntomas reales; suelo radiactivo en el sitio. Considerado por el gobierno canadiense su caso OVNI mejor documentado.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Falcon_Lake_incident']] },
{ id:'cussac-1967', name:'Cussac', date:'1967-08-29', lat:44.98, lng:2.93, loc:'Cussac, Cantal', country:'Francia', type:'CE3', cred:3,
  summary:'Dos niños pastores observaron una esfera brillante y cuatro pequeñas entidades que se elevaron hacia ella. Investigado oficialmente por la gendarmería y luego por GEPAN, que lo mantuvo como no identificado.',
  sources:[['Wikipedia (FR)','https://fr.wikipedia.org/wiki/Rencontre_de_Cussac']] },
{ id:'shag-harbour-1967', name:'Shag Harbour', date:'1967-10-04', lat:43.5, lng:-65.72, loc:'Shag Harbour, Nueva Escocia', country:'Canadá', type:'USO', cred:4,
  summary:'Múltiples testigos vieron un objeto con luces impactar en el agua; barcos hallaron espuma amarilla brillante en la superficie. La Marina canadiense organizó una búsqueda submarina oficial documentada como "OVNI" en los archivos gubernamentales. El "Roswell canadiense".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Shag_Harbour_UFO_incident']] },
{ id:'minot-1968', name:'Minot AFB — B-52', date:'1968-10-24', lat:48.42, lng:-101.36, loc:'Minot AFB, Dakota del Norte', country:'EE.UU.', type:'RV', cred:4,
  summary:'Un B-52 registró en su radar de a bordo un eco enorme que lo acompañó, mientras 16 testigos en tierra (incluido personal de silos nucleares) observaban el objeto. Fotografías del scope de radar conservadas en Blue Book; cerrado oficialmente sin explicación convincente.',
  sources:[['Sitio de investigación del caso','http://www.minotb52ufo.com/'],['NICAP','http://www.nicap.org/681024minot_dir.htm']] },
{ id:'carter-1969', name:'Avistamiento de Jimmy Carter', date:'1969-01-06', lat:31.72, lng:-84.51, loc:'Leary, Georgia', country:'EE.UU.', type:'NL', cred:2,
  summary:'El futuro presidente de EE.UU. y una decena de testigos vieron una luz que cambiaba de color y tamaño antes de un discurso. Carter presentó informe oficial en 1973 y prometió en campaña abrir los archivos OVNI del gobierno.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Jimmy_Carter_UFO_incident']] },

// ------------------------------ 1970s ------------------------------
{ id:'delphos-1971', name:'Anillo de Delphos', date:'1971-11-02', lat:39.27, lng:-97.77, loc:'Delphos, Kansas', country:'EE.UU.', type:'CE2', cred:3,
  summary:'Un adolescente vio un objeto iluminado a baja altura en la granja familiar; quedó un anillo de suelo blanquecino, hidrófobo y fosforescente analizado por varios laboratorios. Premiado como mejor caso del año por el National Enquirer tras evaluación de un panel científico.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Delphos_UFO_incident']] },
{ id:'pascagoula-1973', name:'Abducción de Pascagoula', date:'1973-10-11', lat:30.35, lng:-88.55, loc:'Pascagoula, Mississippi', country:'EE.UU.', type:'CE4', cred:3,
  summary:'Charles Hickson y Calvin Parker relataron ser levitados a un objeto por entidades "robóticas" mientras pescaban. Una grabación policial secreta los captó aterrorizados creyéndose solos, detalle que dio credibilidad al caso. Parker mantuvo el relato hasta su muerte en 2023.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Pascagoula_Abduction']] },
{ id:'coyne-1973', name:'Helicóptero Coyne', date:'1973-10-18', lat:40.78, lng:-82.52, loc:'Mansfield, Ohio', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Un helicóptero UH-1 de la Reserva del Ejército estuvo a punto de colisionar con un objeto gris en forma de puro que lo iluminó con un haz verde; el aparato ascendió 600 m con los mandos en descenso. Cuatro tripulantes militares y testigos en tierra. Premiado como mejor caso por un panel internacional en 1975.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Coyne_incident']] },
{ id:'loring-1975', name:'Incursiones sobre Loring AFB', date:'1975-10-27', lat:46.95, lng:-67.89, loc:'Loring AFB, Maine', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Durante varias noches, objetos no identificados sobrevolaron el área de almacenamiento de armas nucleares de la base, confirmados por radar. Documentado en memorandos NORAD y del Mando Aéreo Estratégico desclasificados vía FOIA; parte de una oleada sobre bases nucleares en 1975.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/1975_Loring_AFB_UFO_sightings'],['Documentos NORAD (Black Vault)','https://www.theblackvault.com/documentarchive/ufos-the-1975-over-flights/']] },
{ id:'travis-walton-1975', name:'Caso Travis Walton', date:'1975-11-05', lat:34.4, lng:-110.79, loc:'Bosque Apache-Sitgreaves, Arizona', country:'EE.UU.', type:'CE4', cred:2,
  summary:'Un leñador desapareció cinco días tras ser alcanzado por un haz de luz ante seis compañeros, que pasaron el polígrafo mientras eran investigados por asesinato. El caso más documentado de presunta abducción con testigos múltiples; origen de la película "Fire in the Sky".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Travis_Walton_incident']] },
{ id:'canarias-1976', name:'Caso Canarias (esfera)', date:'1976-06-22', lat:28.1, lng:-15.6, loc:'Gran Canaria, Islas Canarias', country:'España', type:'MASS', cred:4,
  summary:'Una gigantesca esfera luminosa con presuntas figuras en su interior fue vista por testigos en varias islas, incluidos un médico y la dotación de la corbeta Atrevida de la Armada. Expediente desclasificado por el Ejército del Aire español en los años 90.',
  sources:[['Expedientes OVNI Ejército del Aire (Biblioteca Defensa)','https://bibliotecavirtual.defensa.gob.es/BVMDefensa/expedientes-ovni'],['Wikipedia (ES)','https://es.wikipedia.org/wiki/Avistamientos_ovni_en_Canarias_(1976)']] },
{ id:'tehran-1976', name:'Incidente F-4 de Teherán', date:'1976-09-19', lat:35.69, lng:51.39, loc:'Teherán', country:'Irán', type:'MIL', cred:5,
  summary:'Dos F-4 Phantom iraníes sufrieron pérdidas de instrumentación y armamento al acercarse a un objeto brillante que expulsó un objeto menor hacia uno de ellos. Documentado en un memorando de la DIA distribuido a la Casa Blanca y la NSA, que calificó el caso de "sobresaliente". Referencia obligada de la categoría radar-visual militar.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/1976_Tehran_UFO_incident'],['Memo DIA (Black Vault)','https://www.theblackvault.com/documentarchive/ufo-case-1976-iran-incident/']] },
{ id:'broad-haven-1977', name:'Triángulo de Broad Haven', date:'1977-02-04', lat:51.78, lng:-5.11, loc:'Broad Haven, Gales', country:'Reino Unido', type:'CE3', cred:2,
  summary:'Catorce escolares dibujaron por separado el mismo objeto plateado visto junto a su colegio, dentro de una oleada en Pembrokeshire ("el triángulo galés") documentada en archivos del Ministerio de Defensa británico.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Broad_Haven#UFO_sightings'],['BBC','https://www.bbc.com/news/uk-wales-38854885']] },
{ id:'petrozavodsk-1977', name:'Fenómeno de Petrozavodsk', date:'1977-09-20', lat:61.78, lng:34.36, loc:'Petrozavodsk, Carelia', country:'Rusia (URSS)', type:'MASS', cred:3,
  summary:'Una "medusa" luminosa irradió haces sobre la ciudad ante miles de testigos, coincidiendo con el lanzamiento del satélite Kosmos-955. El evento impulsó la creación del programa secreto soviético de estudio de anomalías (Setka-AN).',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Petrozavodsk_phenomenon']] },
{ id:'colares-1977', name:'Operação Prato — Colares', date:'1977-10-15', lat:-0.94, lng:-48.28, loc:'Colares, Pará', country:'Brasil', type:'CE2', cred:4,
  summary:'Decenas de habitantes de la isla de Colares sufrieron quemaduras y marcas tras ser alcanzados por haces de luz ("chupa-chupa"). La Fuerza Aérea Brasileña desplegó la Operação Prato, que generó cientos de fotos e informes hoy desclasificados; el oficial al mando, Uyrangê Hollanda, confirmó los hechos en 1997.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Opera%C3%A7%C3%A3o_Prato'],['Archivos Arquivo Nacional (Brasil)','https://sian.an.gov.br/']] },
{ id:'emilcin-1978', name:'Abducción de Emilcin', date:'1978-05-10', lat:51.51, lng:22.69, loc:'Emilcin, Lublin', country:'Polonia', type:'CE4', cred:2,
  summary:'El agricultor Jan Wolski declaró haber sido llevado por dos entidades de rasgos asiáticos a un objeto suspendido donde fue examinado. El caso de abducción más célebre de Europa del Este; hay un monumento en el lugar.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Emilcin_abduction']] },
{ id:'valentich-1978', name:'Desaparición de Frederick Valentich', date:'1978-10-21', lat:-39.5, lng:144.8, loc:'Estrecho de Bass, Victoria', country:'Australia', type:'MIL', cred:4,
  summary:'Un piloto de 20 años reportó a control aéreo un objeto metálico con luces verdes maniobrando sobre su Cessna ("no es un avión") antes de que la transmisión terminara con un ruido metálico. Ni el avión ni el piloto aparecieron. Transcripción oficial del Departamento de Transporte australiano conservada.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Disappearance_of_Frederick_Valentich']] },
{ id:'kaikoura-1978', name:'Luces de Kaikoura', date:'1978-12-21', lat:-42.4, lng:173.68, loc:'Kaikoura, Isla Sur', country:'Nueva Zelanda', type:'RV', cred:4,
  summary:'Luces siguieron a aviones de carga Argosy, confirmadas por radar de Wellington y filmadas por un equipo de TV australiano en un segundo vuelo. La RNZAF puso cazas en alerta; el informe oficial atribuyó parte a luces de barcos y Venus, explicación contestada por los pilotos.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Kaikoura_lights']] },
{ id:'zanfretta-1978', name:'Caso Zanfretta', date:'1978-12-06', lat:44.42, lng:9.05, loc:'Torriglia, Liguria', country:'Italia', type:'CE4', cred:1,
  summary:'El vigilante nocturno Fortunato Zanfretta relató varios encuentros con seres altos y un objeto triangular; sus compañeros lo hallaron en shock con la pistola desenfundada. Caso controvertido pero central en la casuística italiana, investigado por los carabinieri.',
  sources:[['Wikipedia (IT)','https://it.wikipedia.org/wiki/Caso_Zanfretta']] },
{ id:'val-johnson-1979', name:'Incidente Val Johnson', date:'1979-08-27', lat:48.34, lng:-96.91, loc:'Condado de Marshall, Minnesota', country:'EE.UU.', type:'CE2', cred:3,
  summary:'El coche patrulla del sheriff adjunto Val Johnson fue golpeado por una luz que dañó parabrisas, antenas y dobló el soporte del faro; ambos relojes del vehículo y del agente se atrasaron 14 minutos. El coche se conserva en un museo del condado. Sin explicación oficial.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Val_Johnson_incident']] },
{ id:'robert-taylor-1979', name:'Incidente de Livingston (Robert Taylor)', date:'1979-11-09', lat:55.88, lng:-3.57, loc:'Dechmont Law, Livingston', country:'Reino Unido', type:'CE2', cred:3,
  summary:'Un guarda forestal fue presuntamente atacado por dos esferas con púas surgidas de un objeto mayor; despertó con la ropa rasgada y marcas en el suelo. Único caso OVNI del Reino Unido investigado como agresión criminal por la policía.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Robert_Taylor_incident']] },
{ id:'manises-1979', name:'Caso Manises', date:'1979-11-11', lat:39.49, lng:-0.47, loc:'Manises, Valencia', country:'España', type:'MIL', cred:4,
  summary:'Un vuelo comercial de TAE con destino Tenerife realizó el primer aterrizaje de emergencia de la historia provocado por un OVNI, tras ser acosado por luces rojas. Un Mirage F-1 del Ejército del Aire despegó y persiguió sin éxito a un objeto que ejecutaba maniobras imposibles. Expediente oficial desclasificado.',
  sources:[['Wikipedia (ES)','https://es.wikipedia.org/wiki/Caso_Manises'],['Expedientes OVNI Defensa','https://bibliotecavirtual.defensa.gob.es/BVMDefensa/expedientes-ovni']] },

// ------------------------------ 1980s ------------------------------
{ id:'la-joya-1980', name:'Oscar Santa María — La Joya', date:'1980-04-11', lat:-16.73, lng:-71.87, loc:'Base aérea La Joya, Arequipa', country:'Perú', type:'MIL', cred:4,
  summary:'El piloto de la FAP Oscar Santa María disparó 64 proyectiles de 30 mm contra un objeto "tipo globo" que resultó ser una estructura metálica con cúpula y que lo superó en maniobra hasta dejarlo sin combustible. Único caso documentado de fuego real contra un OVNI; recogido en un documento de la DIA estadounidense.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Arequipa_UFO_incident'],['Documento DIA (Black Vault)','https://www.theblackvault.com/documentarchive/']] },
{ id:'cash-landrum-1980', name:'Cash–Landrum', date:'1980-12-29', lat:30.05, lng:-94.96, loc:'Huffman, Texas', country:'EE.UU.', type:'CE2', cred:3,
  summary:'Betty Cash, Vickie Landrum y su nieto quedaron expuestos a un objeto romboidal en llamas escoltado por más de 20 helicópteros Chinook. Sufrieron síntomas compatibles con radiación; demandaron al gobierno de EE.UU., que negó tener aparatos en la zona. Caso clave por daños fisiológicos documentados médicamente.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Cash%E2%80%93Landrum_incident']] },
{ id:'rendlesham-1980', name:'Bosque de Rendlesham', date:'1980-12-26', lat:52.09, lng:1.45, loc:'RAF Woodbridge, Suffolk', country:'Reino Unido', type:'MIL', cred:5,
  summary:'Durante dos noches, personal de la USAF (incluido el subcomandante de base, teniente coronel Halt) investigó un objeto triangular con símbolos que dejó huellas y radiación elevada. El "memo Halt" y su grabación en directo son documentos oficiales. El "Roswell británico", citado en audiencias del Congreso de 2023.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Rendlesham_Forest_incident'],['Memo Halt (Archivos UK)','https://www.nationalarchives.gov.uk/ufos/']] },
{ id:'trans-en-provence-1981', name:'Trans-en-Provence', date:'1981-01-08', lat:43.5, lng:6.52, loc:'Trans-en-Provence, Var', country:'Francia', type:'CE2', cred:4,
  summary:'Un objeto con forma de tonel aterrizó en una terraza agrícola ante un testigo y dejó huellas anulares. GEPAN (la agencia oficial francesa) analizó suelo y plantas: compactación a 4-5 toneladas, calentamiento a 300-600 °C y alteraciones bioquímicas en la alfalfa. Probablemente el caso CE2 con mejor análisis de laboratorio de la historia.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Trans-en-Provence_case'],['GEIPAN (CNES)','https://www.cnes-geipan.fr/']] },
{ id:'hessdalen-1984', name:'Luces de Hessdalen', date:'1984-01-01', lat:62.8, lng:11.19, loc:'Valle de Hessdalen', country:'Noruega', type:'NL', cred:4,
  summary:'Fenómeno luminoso recurrente en un valle noruego desde 1981, estudiado por el Proyecto Hessdalen con radares, espectrómetros y estaciones automáticas que siguen activas. El mejor laboratorio natural del mundo para fenómenos luminosos anómalos; sin explicación completa.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Hessdalen_lights'],['Project Hessdalen','http://www.hessdalen.org/']] },
{ id:'hudson-valley-1983', name:'Oleada del valle del Hudson', date:'1983-03-24', lat:41.29, lng:-73.7, loc:'Valle del Hudson, Nueva York', country:'EE.UU.', type:'MASS', cred:3,
  summary:'Entre 1982 y 1986, más de 5.000 personas reportaron un objeto triangular o en bumerán enorme y silencioso sobre Nueva York y Connecticut, incluida una multitud en la autopista Taconic. Investigado por J. Allen Hynek y Philip Imbrogno; la explicación de "avionetas en formación" no convenció a los testigos.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Hudson_Valley_UFO_sightings']] },
{ id:'minsk-1985', name:'Vuelo Aeroflot 8352', date:'1985-09-07', lat:58.0, lng:33.0, loc:'Entre Tbilisi y Tallin (sobre Minsk)', country:'Rusia (URSS)', type:'MIL', cred:3,
  summary:'La tripulación de un Tupolev reportó una nube luminosa con haces que imitó la forma del avión y lo siguió; observado también por otro vuelo y radares. Publicado por la agencia TASS, algo inédito en la URSS, y recogido en la prensa internacional.',
  sources:[['Archivo prensa (AP)','https://apnews.com/']] },
{ id:'dalnegorsk-1986', name:'Colina 611 — Dalnegorsk', date:'1986-01-29', lat:44.56, lng:135.57, loc:'Dalnegorsk, Primorie', country:'Rusia (URSS)', type:'CE2', cred:3,
  summary:'Una esfera rojiza impactó contra la colina 611; científicos soviéticos recuperaron mallas metálicas, esférulas de plomo y "redes" de cuarzo con propiedades anómalas. Conocido como el "Roswell soviético", estudiado por la Academia de Ciencias.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Dalnegorsk_UFO_crash']] },
{ id:'jal1628-1986', name:'Japan Air Lines 1628', date:'1986-11-17', lat:65.0, lng:-148.0, loc:'Sobre Alaska', country:'EE.UU.', type:'RV', cred:5,
  summary:'El capitán Kenju Terauchi reportó dos objetos y una "nave nodriza" del tamaño de dos portaaviones siguiendo a su Boeing 747 de carga durante 50 minutos, con ecos en radar de a bordo y de la FAA. El jefe de la división de accidentes de la FAA, John Callahan, conservó los datos y declaró que la CIA ordenó silencio. Expediente FAA completo disponible.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Japan_Air_Lines_Cargo_Flight_1628_incident'],['Documentos FAA (Black Vault)','https://www.theblackvault.com/documentarchive/japan-airlines-jal1628-ufo-incident-november-17-1986/']] },
{ id:'gulf-breeze-1987', name:'Avistamientos de Gulf Breeze', date:'1987-11-11', lat:30.36, lng:-87.16, loc:'Gulf Breeze, Florida', country:'EE.UU.', type:'DD', cred:1,
  summary:'Ed Walters publicó decenas de fotos nítidas de un objeto con anillo luminoso. Hubo además cientos de avistamientos independientes en la zona durante años. Las fotos de Walters quedaron desacreditadas al hallarse una maqueta en su antigua casa; la oleada local permanece discutida. Incluido como ejemplo de caso contaminado.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Gulf_Breeze_UFO_incident']] },
{ id:'nullarbor-1988', name:'Familia Knowles — Nullarbor', date:'1988-01-20', lat:-31.5, lng:129.0, loc:'Llanura de Nullarbor', country:'Australia', type:'CE2', cred:2,
  summary:'Una familia relató que un objeto luminoso levantó su coche en la carretera Eyre, cubriéndolo de polvo ceniciento y reventando un neumático. Muestras analizadas; el caso abrió telediarios en Australia y el coche fue examinado por la policía.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Knowles_family_UFO_incident']] },
{ id:'voronezh-1989', name:'Voronezh (parque)', date:'1989-09-27', lat:51.67, lng:39.21, loc:'Voronezh', country:'Rusia (URSS)', type:'CE3', cred:2,
  summary:'Decenas de niños y adultos reportaron una esfera rosada de la que descendieron seres de tres metros con un "robot". Publicado por TASS como noticia oficial, generando titulares mundiales. Investigado por científicos locales con análisis de suelo.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Voronezh_UFO_incident'],['NYT 1989','https://www.nytimes.com/1989/10/11/world/tass-tells-of-space-aliens-pravda-is-silent.html']] },
{ id:'belgian-eupen-1989', name:'Ola belga — Eupen', date:'1989-11-29', lat:50.63, lng:6.03, loc:'Eupen, Lieja', country:'Bélgica', type:'MASS', cred:4,
  summary:'Dos gendarmes y decenas de testigos observaron un triángulo silencioso con tres focos sobre Eupen, inicio de una oleada con más de 2.000 reportes en año y medio. La gendarmería y el ejército belga colaboraron abiertamente con los investigadores civiles (SOBEPS): un caso único de transparencia oficial.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Belgian_UFO_wave']] },
{ id:'belgian-f16-1990', name:'Ola belga — persecución F-16', date:'1990-03-30', lat:50.6, lng:4.5, loc:'Valonia', country:'Bélgica', type:'RV', cred:4,
  summary:'Dos F-16 de la Fuerza Aérea Belga persiguieron ecos de radar que ejecutaban aceleraciones de hasta 40 g, correlacionados con radares de tierra de la OTAN. El jefe del Estado Mayor del Aire, general De Brouwer, presentó los datos públicamente y mantiene el caso como no identificado.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Belgian_UFO_wave'],['Informe SOBEPS (resumen)','https://www.cobeps.org/']] },

// ------------------------------ 1990s ------------------------------
{ id:'mexico-eclipse-1991', name:'Eclipse de Ciudad de México', date:'1991-07-11', lat:19.43, lng:-99.13, loc:'Ciudad de México', country:'México', type:'MASS', cred:2,
  summary:'Durante el eclipse total de sol, miles de personas filmaron un objeto plateado estacionario sobre la capital, dando inicio a la oleada mexicana de los 90 popularizada por Jaime Maussan. Los escépticos identifican a Venus en muchas grabaciones; otras siguen discutidas.',
  sources:[['Wikipedia (ES)','https://es.wikipedia.org/wiki/Avistamiento_ovni_en_M%C3%A9xico_de_1991']] },
{ id:'cosford-1993', name:'Incidente Cosford/Shawbury', date:'1993-03-31', lat:52.63, lng:-2.3, loc:'RAF Cosford, Shropshire', country:'Reino Unido', type:'MIL', cred:4,
  summary:'Policías, militares y el meteorólogo de RAF Shawbury reportaron un objeto enorme y lento con haz de luz barriendo el suelo. Nick Pope, responsable del "UFO desk" del Ministerio de Defensa, lo investigó oficialmente y lo considera su mejor caso; el informe llegó al jefe del Estado Mayor del Aire.',
  sources:[['Archivos UFO del MoD (National Archives)','https://www.nationalarchives.gov.uk/ufos/']] },
{ id:'ariel-1994', name:'Colegio Ariel — Ruwa', date:'1994-09-16', lat:-17.36, lng:31.34, loc:'Ruwa', country:'Zimbabue', type:'CE3', cred:3,
  summary:'62 alumnos de un colegio rural vieron un objeto aterrizado y entidades de ojos grandes junto a él durante el recreo; varios relataron "mensajes" sobre el daño al planeta. Entrevistados días después por el psiquiatra de Harvard John E. Mack y por la BBC. Los testigos, ya adultos, mantienen el relato (documental "Ariel Phenomenon").',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Ariel_School_UFO_incident'],['BBC (archivo)','https://www.bbc.com/news/world-africa-62064633']] },
{ id:'bariloche-1995', name:'Caso Bariloche', date:'1995-07-31', lat:-41.15, lng:-71.31, loc:'San Carlos de Bariloche, Río Negro', country:'Argentina', type:'MIL', cred:3,
  summary:'Un Boeing 727 de Aerolíneas Argentinas en aproximación a Bariloche fue acompañado por un objeto luminoso mientras la ciudad sufría un apagón; la torre y un avión de la Fuerza Aérea confirmaron la observación. Caso emblemático de la aviación comercial argentina.',
  sources:[['Wikipedia (ES)','https://es.wikipedia.org/wiki/Incidente_ovni_de_Bariloche']] },
{ id:'varginha-1996', name:'Caso Varginha', date:'1996-01-20', lat:-21.55, lng:-45.43, loc:'Varginha, Minas Gerais', country:'Brasil', type:'CE3', cred:2,
  summary:'Tres jóvenes reportaron una criatura marrón de ojos rojos; testimonios posteriores hablan de capturas por militares y un hospital acordonado. El ejército brasileño lo niega; el caso fue tratado en el Senado de Brasil y sigue generando documentales ("Moment of Contact", 2022).',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Varginha_UFO_incident']] },
{ id:'yukon-1996', name:'OVNI gigante del Yukón', date:'1996-12-11', lat:62.0, lng:-136.3, loc:'Fox Lake — Carmacks, Yukón', country:'Canadá', type:'NL', cred:3,
  summary:'Más de 30 testigos a lo largo de 200 km de la autopista Klondike describieron un objeto con hileras de luces estimado en cientos de metros. Investigación civil exhaustiva con reconstrucción triangulada; los escépticos proponen la reentrada del cohete de un satélite.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Yukon_UFO_sighting']] },
{ id:'phoenix-1997', name:'Luces de Phoenix', date:'1997-03-13', lat:33.45, lng:-112.07, loc:'Phoenix, Arizona', country:'EE.UU.', type:'MASS', cred:4,
  summary:'Miles de personas observaron una formación en V silenciosa y kilométrica cruzar Arizona, y horas después una hilera de luces sobre Phoenix (bengalas militares según la USAF). El gobernador Fife Symington ridiculizó el caso en rueda de prensa y una década después admitió haber visto el objeto: "era algo de otro mundo".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Phoenix_Lights'],['CNN — Symington','https://edition.cnn.com/2007/US/03/21/symington.ufocommentary/']] },

// ------------------------------ 2000s ------------------------------
{ id:'illinois-2000', name:'Triángulo del sur de Illinois', date:'2000-01-05', lat:38.55, lng:-89.98, loc:'Highland — Lebanon, Illinois', country:'EE.UU.', type:'CE1', cred:4,
  summary:'Cinco policías de municipios distintos siguieron por radio un objeto triangular enorme y silencioso a baja altura. Las comunicaciones de los despachos quedaron grabadas. Caso de referencia de los "triángulos negros"; documental "The Edge of Reality".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Black_triangle_(UFO)'],['NUFORC','https://nuforc.org/']] },
{ id:'campeche-2004', name:'FLIR de Campeche (FAM)', date:'2004-03-05', lat:19.0, lng:-90.5, loc:'Sobre Campeche', country:'México', type:'MIL', cred:3,
  summary:'Un avión de vigilancia antinarcóticos de la Fuerza Aérea Mexicana filmó en infrarrojo 11 fuentes de calor que lo rodearon, invisibles a simple vista. El secretario de Defensa hizo público el vídeo: primera desclasificación oficial de este tipo en América. Explicación propuesta: llamaradas de plataformas petroleras Cantarell.',
  sources:[['Wikipedia (ES)','https://es.wikipedia.org/wiki/Avistamiento_de_ovnis_en_Campeche']] },
{ id:'tinley-park-2004', name:'Luces de Tinley Park', date:'2004-08-21', lat:41.57, lng:-87.79, loc:'Tinley Park, Illinois', country:'EE.UU.', type:'MASS', cred:3,
  summary:'Tres luces rojas en formación triangular lenta fueron vistas y grabadas en vídeo por cientos de testigos en el área de Chicago, repitiéndose en fechas posteriores. Uno de los avistamientos masivos con más grabaciones independientes cruzadas.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Tinley_Park_Lights']] },
{ id:'nimitz-2004', name:'USS Nimitz — "Tic Tac" (FLIR1)', date:'2004-11-14', lat:31.0, lng:-117.6, loc:'Frente a San Diego, Pacífico', country:'EE.UU.', type:'MIL', cred:5,
  summary:'El crucero USS Princeton rastreó durante días objetos que caían de 24.000 m al nivel del mar en segundos. Los F/A-18 del comandante David Fravor y la teniente Alex Dietrich interceptaron un objeto blanco "tipo Tic Tac" sin alas que los superó en maniobra y reapareció en su punto de encuentro secreto. Vídeo FLIR1 desclasificado por el Pentágono en 2020; Fravor testificó bajo juramento ante el Congreso en 2023. El caso UAP moderno por excelencia.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/USS_Nimitz_UFO_incident'],['Vídeo oficial (Navy/DoD)','https://www.navair.navy.mil/foia/documents'],['NYT 2017','https://www.nytimes.com/2017/12/16/us/politics/pentagon-program-ufo-harry-reid.html']],
  media:[{k:'video', commons:'FLIR1 Official UAP Footage from the USG for Public Release.webm', cap:'Vídeo "FLIR1" — desclasificado oficialmente por el Pentágono (US Navy/DoD, dominio público)'}] },
{ id:'ohare-2006', name:'Aeropuerto O\'Hare de Chicago', date:'2006-11-07', lat:41.98, lng:-87.9, loc:'Aeropuerto O\'Hare, Chicago', country:'EE.UU.', type:'DD', cred:3,
  summary:'Empleados de United Airlines y pilotos observaron un disco metálico gris suspendido sobre la puerta C-17, que ascendió perforando un agujero nítido en las nubes. La FAA lo atribuyó a un "fenómeno meteorológico" sin investigar; la grabación de la llamada del supervisor a la torre se obtuvo vía FOIA.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/2006_O%27Hare_International_Airport_UFO_sighting'],['Chicago Tribune','https://www.chicagotribune.com/2007/01/01/in-the-sky-a-bird-a-plane-a-ufo/']] },
{ id:'alderney-2007', name:'Avistamiento de Alderney', date:'2007-04-23', lat:49.72, lng:-2.2, loc:'Canal de la Mancha, cerca de Alderney', country:'Reino Unido', type:'MIL', cred:3,
  summary:'Dos pilotos comerciales en vuelos distintos observaron durante 15 minutos dos enormes objetos amarillos brillantes estacionarios sobre el Canal; pasajeros también los vieron. Estudiado en un informe técnico independiente de 180 páginas; sin explicación.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/2007_Alderney_UFO_sighting']] },
{ id:'stephenville-2008', name:'Stephenville', date:'2008-01-08', lat:32.22, lng:-98.2, loc:'Stephenville, Texas', country:'EE.UU.', type:'RV', cred:4,
  summary:'Decenas de testigos, incluido un piloto y un agente, vieron luces enormes y silenciosas. Los datos de radar de la FAA obtenidos vía FOIA por MUFON mostraron un objeto sin transpondedor dirigiéndose hacia el rancho de George W. Bush, con cazas F-16 cuya presencia la USAF primero negó y luego admitió.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Stephenville,_Texas#2008_UFO_sightings'],['Informe radar MUFON (resumen)','https://www.theblackvault.com/documentarchive/stephenville-texas-ufo-incident-radar-analysis/']] },
{ id:'kumburgaz-2008', name:'Vídeos de Kumburgaz', date:'2008-05-13', lat:41.0, lng:28.48, loc:'Kumburgaz, Estambul', country:'Turquía', type:'NL', cred:1,
  summary:'Un vigilante grabó durante varias noches objetos sobre el mar de Mármara con un zoom potente; el consejo científico turco TÜBITAK declaró los vídeos genuinos. Los escépticos los identifican como un crucero iluminado desenfocado. Incluido como caso famoso de evidencia ambigua en vídeo.',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/Kumburgaz_UFO_sightings']] },

// ------------------------------ 2010s ------------------------------
{ id:'el-bosque-2010', name:'Festival aéreo de El Bosque', date:'2010-11-05', lat:-33.56, lng:-70.69, loc:'Base aérea El Bosque, Santiago', country:'Chile', type:'MIL', cred:3,
  summary:'Varias cámaras grabaron un objeto cruzando a gran velocidad entre los cazas durante una exhibición aérea. Analizado por el CEFAA, el organismo oficial chileno de estudio de fenómenos aéreos anómalos; conclusiones discutidas (posible insecto cercano al objetivo).',
  sources:[['Wikipedia (CEFAA)','https://en.wikipedia.org/wiki/CEFAA']] },
{ id:'xiaoshan-2010', name:'Cierre del aeropuerto de Xiaoshan', date:'2010-07-07', lat:30.23, lng:120.43, loc:'Hangzhou, Zhejiang', country:'China', type:'NL', cred:2,
  summary:'El aeropuerto de Hangzhou suspendió operaciones una hora tras detectar la tripulación de un vuelo un objeto no identificado; 18 vuelos desviados. Las autoridades dijeron conocer la causa pero no la revelaron por "implicar secretos militares".',
  sources:[['Wikipedia','https://en.wikipedia.org/wiki/2010_Xiaoshan_Airport_UFO_sighting'],['ABC News','https://abcnews.go.com/International/ufo-sighting-closes-chinese-airport/story?id=11163838']] },
{ id:'aguadilla-2013', name:'Aguadilla (vídeo DHS)', date:'2013-04-25', lat:18.5, lng:-67.13, loc:'Aguadilla, Puerto Rico', country:'EE.UU.', type:'USO', cred:4,
  summary:'La cámara térmica de un avión de Aduanas y Protección de Fronteras grabó un objeto que sobrevoló el aeropuerto, entró y salió del mar sin frenar y pareció dividirse en dos. Análisis técnico exhaustivo del grupo SCU (Scientific Coalition for UAP Studies). Caso transmedio de referencia.',
  sources:[['Informe SCU','https://www.explorescu.org/post/2013-aguadilla-puerto-rico'],['Wikipedia','https://en.wikipedia.org/wiki/List_of_reported_UFO_sightings']] },
{ id:'chile-navy-2014', name:'FLIR de la Armada chilena', date:'2014-11-11', lat:-33.2, lng:-71.6, loc:'Costa de Valparaíso', country:'Chile', type:'MIL', cred:3,
  summary:'Un helicóptero naval grabó en infrarrojo un objeto que parecía expulsar una estela caliente. El CEFAA lo publicó tras dos años de análisis como "no identificado"; investigadores independientes lo identificaron después como un vuelo comercial IB6830. Ejemplo de cómo un caso oficial puede resolverse con datos abiertos.',
  sources:[['Artículo resolución (Metabunk)','https://www.metabunk.org/threads/explained-chilean-navy-infrared-video-of-ufo-ib6830-and-a350-or-a340.8313/']] },
{ id:'gimbal-2015', name:'USS Theodore Roosevelt — "Gimbal"', date:'2015-01-21', lat:30.5, lng:-79.0, loc:'Costa este, Atlántico (Florida-Georgia)', country:'EE.UU.', type:'MIL', cred:5,
  summary:'Aviadores del ala aérea del Roosevelt grabaron el vídeo "Gimbal": un objeto sin alas ni escape que rota sobre su eje contra el viento, junto a una formación de 4-6 objetos. Los pilotos Ryan Graves y otros reportaron detecciones diarias tras la mejora de los radares AESA. Desclasificado por el Pentágono en 2020; Graves testificó ante el Congreso en 2023.',
  sources:[['Wikipedia (Pentagon UFO videos)','https://en.wikipedia.org/wiki/Pentagon_UFO_videos'],['NYT 2019','https://www.nytimes.com/2019/05/26/us/politics/ufo-sightings-navy-pilots.html']],
  media:[{k:'video', commons:'Gimbal The First Official UAP Footage from the USG for Public Release.webm', cap:'Vídeo "Gimbal" — desclasificado oficialmente por el Pentágono (US Navy/DoD, dominio público)'}] },
{ id:'gofast-2015', name:'"GoFast" (costa este)', date:'2015-01-21', lat:31.5, lng:-78.0, loc:'Costa este, Atlántico', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Tercer vídeo desclasificado por el Pentágono: un objeto blanco aparentemente rasante sobre el mar captado por el ATFLIR de un F/A-18. El análisis paralático sugiere que volaba más alto y lento de lo que aparenta; el propio AARO lo considera probable efecto de paralaje. Incluido como ejemplo de análisis riguroso de datos oficiales.',
  sources:[['Wikipedia (Pentagon UFO videos)','https://en.wikipedia.org/wiki/Pentagon_UFO_videos'],['AARO','https://www.aaro.mil/']],
  media:[{k:'video', commons:'Go Fast Official USG Footage of UAP for Public Release.webm', cap:'Vídeo "GoFast" — desclasificado oficialmente por el Pentágono (US Navy/DoD, dominio público)'}] },
{ id:'uss-russell-2019', name:'USS Russell — "pirámides"', date:'2019-07-15', lat:33.2, lng:-119.5, loc:'Islas del Canal, California', country:'EE.UU.', type:'MIL', cred:3,
  summary:'Durante ejercicios frente a California, varios destructores fueron sobrevolados noches consecutivas por enjambres de objetos; un vídeo nocturno mostró formas "piramidales" (probable bokeh de luces parpadeantes). La Marina confirmó la autenticidad de las imágenes; la investigación interna apunta a drones no atribuidos. Caso clave del problema dron/UAP.',
  sources:[['The Drive / War Zone','https://www.twz.com/40054/navy-confirms-videos-of-unidentified-aircraft-swarming-its-warships-are-real'],['Wikipedia','https://en.wikipedia.org/wiki/List_of_reported_UFO_sightings']] },
{ id:'omaha-2019', name:'USS Omaha — esfera transmedio', date:'2019-07-15', lat:32.5, lng:-119.8, loc:'Frente a San Diego, Pacífico', country:'EE.UU.', type:'USO', cred:3,
  summary:'El CIC del USS Omaha grabó una esfera oscura que, tras maniobrar, se introdujo en el mar sin desaceleración aparente; no se recuperaron restos. Imágenes confirmadas como auténticas por el Pentágono e incluidas en el expediente UAP presentado al Congreso.',
  sources:[['Mystery Wire / vídeo verificado','https://www.mysterywire.com/ufo/omaha-sphere-video/'],['Wikipedia (USS Omaha)','https://en.wikipedia.org/wiki/USS_Omaha_(LCS-12)']] },

// ------------------------------ 2020s ------------------------------
{ id:'aa2292-2021', name:'American Airlines 2292 — "misil largo y cilíndrico"', date:'2021-02-21', lat:34.5, lng:-104.5, loc:'Sobre el noreste de Nuevo México', country:'EE.UU.', type:'MIL', cred:3,
  summary:'La tripulación de un Airbus A320 radió a Albuquerque: "tenemos un objeto largo y cilíndrico que casi nos pasa por encima... se movía muy rápido". La grabación fue interceptada por un radioaficionado y American Airlines confirmó su autenticidad. El FBI declinó comentar; sin tráfico militar reconocido en la zona.',
  sources:[['The War Zone','https://www.twz.com/39426/airliner-crew-reports-bizarre-encounter-with-cylindrical-object-over-new-mexico'],['Snopes (verificación)','https://www.snopes.com/fact-check/american-airlines-ufo-sighting/']] },
{ id:'lake-huron-2023', name:'Derribo sobre el lago Hurón', date:'2023-02-12', lat:44.5, lng:-82.5, loc:'Lago Hurón, Míchigan', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Un F-16 derribó con un misil AIM-9X un objeto octogonal lento a 6.000 m, uno de los tres objetos no identificados derribados ese febrero tras el globo espía chino (Alaska el día 10, Yukón el 11). El primer misil falló. Los restos nunca se recuperaron y la Casa Blanca cerró el episodio sin identificación pública. Primer derribo reconocido de un objeto no identificado sobre EE.UU.',
  sources:[['AP News','https://apnews.com/article/politics-united-states-government-michigan-lake-huron-d0a4a92e1fee4036e2cef1711d959cca'],['Wikipedia','https://en.wikipedia.org/wiki/2023_high-altitude_object_events']] },
{ id:'langley-2023', name:'Incursiones de drones — Langley AFB', date:'2023-12-06', lat:37.08, lng:-76.36, loc:'Langley AFB, Virginia', country:'EE.UU.', type:'MIL', cred:4,
  summary:'Durante 17 noches, enjambres de objetos no identificados sobrevolaron impunemente una de las bases de cazas más importantes de EE.UU., forzando el traslado de F-22. Documentado vía FOIA y reconocido por el Pentágono; el origen sigue oficialmente sin atribuir. Paradigma del solapamiento dron-UAP en la seguridad nacional.',
  sources:[['The War Zone','https://www.twz.com/news-features/mysterious-drone-swarms-over-langley-afb-prompted-special-response-task-force'],['CNN','https://edition.cnn.com/2024/10/12/politics/mystery-drones-swarmed-langley-air-force-base/index.html']] },
{ id:'nj-drones-2024', name:'Oleada de drones de Nueva Jersey', date:'2024-12-01', lat:40.22, lng:-74.55, loc:'Nueva Jersey (estado)', country:'EE.UU.', type:'MASS', cred:3,
  summary:'Miles de reportes de grandes "drones" nocturnos sobre Nueva Jersey y estados vecinos durante semanas, sobrevolando infraestructura crítica. El FBI recibió más de 5.000 avisos; la Casa Blanca atribuyó la mayoría a aeronaves legales mal identificadas, sin convencer a gobernadores ni congresistas. Caso de estudio de pánico, vacío informativo y límites de la atribución.',
  sources:[['AP News','https://apnews.com/hub/drones'],['Wikipedia','https://en.wikipedia.org/wiki/2024_United_States_drone_sightings']] },

// ------- Desclasificación PURSUE (Pentágono, 2026) — casos con metraje oficial -------
{ id:'harare-airport-2008', name:'Disco del aeropuerto de Harare', date:'2008-07-01', lat:-17.93, lng:31.09, loc:'Aeropuerto Internacional de Harare', country:'Zimbabue', type:'DD', cred:3,
  summary:'Caso incluido en los archivos desclasificados por el Pentágono en 2026 (sistema PURSUE): un objeto con forma de disco, centro hueco y luces giratorias observado en el aeropuerto de Harare. El reporte fue transmitido en su día a la Sala de Situación de la Casa Blanca, detalle que revela el seguimiento de incidentes UAP internacionales.',
  sources:[['CBS News — 3ª tanda PURSUE','https://www.cbsnews.com/news/ufo-files-pentagon-3rd-release-documents-videos/'],['Portal oficial WAR.GOV/UFO','https://www.war.gov/ufo']] },
{ id:'pursue-western-2021', name:'Esfera del desierto (DOW-UAP-PR061)', date:'2021-04-12', lat:37.0, lng:-115.2, loc:'Oeste de EE.UU. (ubicación exacta no divulgada)', country:'EE.UU.', type:'MIL', cred:3,
  summary:'Vídeo oficial desclasificado en 2026. Un pequeño objeto esférico luminoso sobre el desierto del oeste de EE.UU. exhibe control direccional y un aparente "comportamiento de ocultación". Catalogado por AARO como DOW-UAP-PR061. Coordenadas aproximadas a la región divulgada.',
  sources:[['Vídeo oficial (Wikimedia Commons, dominio público)','https://commons.wikimedia.org/wiki/File:Western_USA_2021_UAP_Official_Footage_from_the_USG_for_Public_Release.webm'],['The Debrief — análisis PURSUE','https://thedebrief.org/the-pentagon-just-released-its-third-batch-of-uap-files-what-have-we-learned-from-the-pursue-releases-so-far/']],
  media:[{k:'video', commons:'Western USA 2021 UAP Official Footage from the USG for Public Release.webm', cap:'Metraje oficial AARO — oeste de EE.UU., 2021 (dominio público, tanda PURSUE 2026)'}] },
{ id:'pursue-midest-2022', name:'Orbe de Oriente Medio (FLIR)', date:'2022-07-12', lat:33.31, lng:44.36, loc:'Oriente Medio (región; ubicación exacta no divulgada)', country:'—', type:'MIL', cred:3,
  summary:'Grabación infrarroja desde una plataforma militar estadounidense desclasificada por el Pentágono en 2026. Un objeto esférico se desplaza sin firma de propulsión visible. AARO no ha ofrecido una resolución pública. Coordenadas aproximadas a la región.',
  sources:[['Vídeo oficial (Wikimedia Commons, dominio público)','https://commons.wikimedia.org/wiki/File:MiddleEast_UAP_20220712_Official_Footage_from_the_USG_for_Public_Release.webm'],['Portal oficial WAR.GOV/UFO','https://www.war.gov/ufo']],
  media:[{k:'video', commons:'MiddleEast UAP 20220712 Official Footage from the USG for Public Release.webm', cap:'Metraje oficial AARO — Oriente Medio, 12/07/2022 (dominio público, tanda PURSUE 2026)'}] },
{ id:'pursue-southasia-2023', name:'Orbe del sur de Asia', date:'2023-01-15', lat:27.5, lng:70.5, loc:'Sur de Asia (región; ubicación exacta no divulgada)', country:'—', type:'MIL', cred:3,
  summary:'Uno de los vídeos infrarrojos liberados en la serie PURSUE de 2026: un objeto esférico captado por sensores militares estadounidenses sobre el sur de Asia. Sin resolución oficial publicada. Coordenadas aproximadas a la región divulgada.',
  sources:[['Vídeo oficial (Wikimedia Commons, dominio público)','https://commons.wikimedia.org/wiki/File:SouthAsia_1_UAP_20230115_Official_Footage_from_the_USG_for_Public_Release.webm'],['Portal oficial WAR.GOV/UFO','https://www.war.gov/ufo']],
  media:[{k:'video', commons:'SouthAsia 1 UAP 20230115 Official Footage from the USG for Public Release.webm', cap:'Metraje oficial AARO — sur de Asia, 15/01/2023 (dominio público, tanda PURSUE 2026)'}] },
{ id:'pursue-orbs-2023', name:'Orbe "nodriza" del oeste de EE.UU.', date:'2023-10-01', lat:39.2, lng:-111.8, loc:'Oeste de EE.UU. (ubicación exacta no divulgada)', country:'EE.UU.', type:'NL', cred:3,
  summary:'Caso estrella de la 3ª tanda PURSUE (2026): cinco agentes federales describen una gran luz naranja de la que "nacían" orbes rojos más pequeños de forma repetida. Uno preguntó a su compañero: "¿estás viendo esto?". Los orbes rojos aceleraban al instante y maniobraban en formación horizontal coordinada. Coordenadas aproximadas a la región divulgada.',
  sources:[['CBS News — 3ª tanda PURSUE','https://www.cbsnews.com/news/ufo-files-pentagon-3rd-release-documents-videos/'],['Newsweek — 5 revelaciones','https://www.newsweek.com/ufo-files-pentagon-releases-third-batch-records-uap-pete-hegseth-trump-12064856']] },
{ id:'colorado-springs-2022', name:'Objeto opalescente de Colorado Springs', date:'2022-01-01', lat:38.74, lng:-104.85, loc:'Cerca de Cheyenne Mountain, Colorado Springs', country:'EE.UU.', type:'DD', cred:2,
  summary:'Incluido en los archivos PURSUE de 2026: un objeto con forma de "patata", color blanquecino opalescente y paneles articulados, observado cerca del complejo de Cheyenne Mountain. AARO lo evaluó con "baja confianza" como retrodispersión de luz solar — un buen ejemplo del principio del residuo: incluso en una tanda histórica, parte de los casos tienen explicación prosaica probable.',
  sources:[['CBS News — 3ª tanda PURSUE','https://www.cbsnews.com/news/ufo-files-pentagon-3rd-release-documents-videos/'],['The Debrief — análisis PURSUE','https://thedebrief.org/the-pentagon-just-released-its-third-batch-of-uap-files-what-have-we-learned-from-the-pursue-releases-so-far/']] },

// ------------------------------ España / Islas Baleares ------------------------------
{ id:'haussmann-mallorca-1950', name:'Fotos de Haussmann (Mallorca)', date:'1950-03-26', lat:39.58, lng:3.03, loc:'Entre Montuïri y Vilafranca de Bonany, Mallorca', country:'España', type:'DD', cred:2,
  summary:'El fotógrafo alemán afincado en Mallorca Heinrich (Enrique) Haussmann fotografió con su cámara Linhof lo que describió como un gran disco giratorio que cruzó el cielo de este a oeste emitiendo un zumbido. Publicadas en el diario Baleares, fueron de las primeras fotos de un OVNI con repercusión nacional en España. Su autenticidad se debate desde entonces; figuran en el catálogo FOTOCAT de Ballester Olmos.',
  sources:[['Última Hora — "ovnimanía" en Mallorca','https://www.ultimahora.es/noticias/local/2023/02/19/1884911/ovnis-mallorca-hace-mas-anos-desato-ovnimania-avistamientos.html'],['UFO FOTOCAT (Ballester Olmos)','https://fotocat.blogspot.com/']] },
{ id:'iberia435-1969', name:'Vuelo Iberia 435 (Palma–Madrid)', date:'1969-07-28', lat:39.55, lng:2.30, loc:'Sobre el Mediterráneo, al oeste de Mallorca', country:'España', type:'MIL', cred:2,
  summary:'La tripulación de una Caravelle de Iberia (comandante Jaime Ordovás) reportó a 26.000 pies una luz blanca cegadora que adoptó forma triangular antes de desaparecer. El Ejército del Aire interrogó a los pilotos y archivó el caso; la conclusión oficial fue el planeta Venus. Ejemplo clásico del filtrado escéptico de los expedientes españoles.',
  sources:[['Expedientes OVNI Ejército del Aire (Biblioteca de Defensa)','https://bibliotecavirtual.defensa.gob.es/BVMDefensa/es/consulta/registro.do?id=42382'],['Última Hora','https://www.ultimahora.es/noticias/local/2023/02/19/1884911/ovnis-mallorca-hace-mas-anos-desato-ovnimania-avistamientos.html']] },
{ id:'soller-1979', name:'Fotos de Sóller (l\'Ofre)', date:'1979-11-12', lat:39.78, lng:2.74, loc:'L\'Ofre, Sóller, Serra de Tramuntana, Mallorca', country:'España', type:'NL', cred:3,
  summary:'La misma madrugada del Caso Manises, el mecánico Pep Climent fotografió dos potentes luces rojas sobre la Serra de Tramuntana desde l\'Ofre. El caso se integró en el expediente desclasificado por el Ejército del Aire; al desclasificarse, el autor reclamó formalmente los negativos al Mando Aéreo. Sóller fue durante décadas el punto más activo de la casuística balear.',
  sources:[['Expedientes OVNI Ejército del Aire (Biblioteca de Defensa)','https://bibliotecavirtual.defensa.gob.es/BVMDefensa/es/consulta/registro.do?id=42382'],['Última Hora','https://www.ultimahora.es/noticias/local/2023/02/19/1884911/ovnis-mallorca-hace-mas-anos-desato-ovnimania-avistamientos.html'],['Caso Manises (Wikipedia)','https://es.wikipedia.org/wiki/Incidente_ovni_de_Manises']] },
{ id:'menorca-1989', name:'Destellos del noreste de Menorca', date:'1989-11-15', lat:40.02, lng:4.20, loc:'Noreste de Menorca', country:'España', type:'NL', cred:2,
  summary:'Entre noviembre de 1989 y febrero de 1990, varios testigos del noreste de Menorca describieron destellos intensos que se transformaban en un objeto circular flotando a baja altura, con un movimiento de rotación sobre su propio eje. Oleada local recogida por la casuística balear.',
  sources:[['Última Hora — avistamientos en Baleares','https://www.ultimahora.es/noticias/local/2023/02/19/1884911/ovnis-mallorca-hace-mas-anos-desato-ovnimania-avistamientos.html']] },
{ id:'cala-tuent-1991', name:'Caso Jomel (Cala Tuent)', date:'1991-08-15', lat:39.84, lng:2.80, loc:'Cala Tuent, Escorca, Mallorca', country:'España', type:'CE3', cred:1,
  summary:'José María Gómez Montiel ("Jomel") relató haber visto en Cala Tuent un gran objeto luminoso junto a una figura humanoide encapuchada; él y su acompañante huyeron. Caso de encuentro cercano muy discutido y sin corroboración independiente, incluido por su peso en el folclore ufológico balear.',
  sources:[['Última Hora — "ovnimanía" en Mallorca','https://www.ultimahora.es/noticias/local/2023/02/19/1884911/ovnis-mallorca-hace-mas-anos-desato-ovnimania-avistamientos.html']] },
];

// Disclosure timeline (US-focused) for the knowledge hub
const DISCLOSURE_TIMELINE = [
  { year:'1947', title:'Memo Twining / Proyecto Sign', text:'Tras la oleada de 1947, el general Nathan Twining escribe que "el fenómeno es algo real y no visionario o ficticio". Nace Proyecto Sign, primera investigación oficial de la USAF.' },
  { year:'1948', title:'"Estimate of the Situation"', text:'Proyecto Sign concluye en un documento (luego destruido) que la mejor explicación es interplanetaria. El general Vandenberg lo rechaza; Sign es sustituido por el escéptico Proyecto Grudge.' },
  { year:'1952', title:'Proyecto Blue Book', text:'La USAF crea Blue Book, que recopilará 12.618 casos hasta 1969, 701 de ellos nunca identificados. La oleada de Washington D.C. fuerza la mayor rueda de prensa del Pentágono desde la guerra.' },
  { year:'1953', title:'Panel Robertson (CIA)', text:'Un panel secreto de la CIA recomienda "desmitificar" los OVNIs y vigilar a los grupos civiles: la gestión del fenómeno pasa a ser un asunto de control de percepción pública.' },
  { year:'1966', title:'Comité Condon', text:'Tras el escándalo del "gas de pantano" y la presión del congresista Gerald Ford, la USAF encarga a la Universidad de Colorado un estudio "independiente". Su conclusión negativa (1968) justificará el cierre de Blue Book, pese a que ~30% de sus propios casos quedaron sin explicar.' },
  { year:'1969', title:'Cierre de Blue Book', text:'La USAF cancela Blue Book: ningún OVNI evaluado representa amenaza ni evidencia de tecnología extraterrestre. Oficialmente, EE.UU. deja de investigar... durante décadas, según la versión pública.' },
  { year:'1974–', title:'Era FOIA', text:'La Ley de Libertad de Información permite a investigadores civiles (CAUS, NICAP, luego Black Vault) extraer miles de documentos de CIA, NSA, DIA y FBI que muestran interés continuado pese al cierre oficial.' },
  { year:'2007', title:'AATIP / AAWSAP', text:'A instancias del senador Harry Reid, el Pentágono financia con 22 M$ el programa AAWSAP/AATIP, gestionado con Bigelow Aerospace, para estudiar incidentes UAP militares. Lo dirigirá Luis Elizondo hasta su dimisión en 2017.' },
  { year:'2017', title:'El artículo del New York Times', text:'El 16/12/2017, el NYT revela AATIP y publica los vídeos FLIR1 y Gimbal. Punto de inflexión: el estigma mediático empieza a romperse y nace la organización TTSA de Tom DeLonge, Elizondo y Chris Mellon.' },
  { year:'2019', title:'La Marina cambia las reglas', text:'La US Navy confirma que los vídeos muestran "fenómenos aéreos no identificados" reales y crea nuevos protocolos de reporte para pilotos, admitiendo que el estigma suprimía los informes.' },
  { year:'2020', title:'Desclasificación oficial y UAPTF', text:'El Pentágono publica oficialmente FLIR1, Gimbal y GoFast y crea la UAP Task Force en la Marina. El Congreso exige un informe público en la ley de inteligencia.' },
  { year:'2021', title:'Informe ODNI', text:'El 25/6/2021, la Oficina del Director de Inteligencia Nacional publica su evaluación preliminar: de 144 casos militares, solo 1 explicado; 18 mostraban "características de vuelo inusuales". Los UAP son declarados problema de seguridad aérea y nacional.' },
  { year:'2022', title:'AARO y primera audiencia en 50 años', text:'En mayo, el Congreso celebra la primera audiencia pública sobre UAP desde 1968. El Pentágono crea AARO (All-domain Anomaly Resolution Office) bajo el físico Sean Kirkpatrick, con mandato sobre aire, mar, espacio y transmedio.' },
  { year:'2023', title:'Grusch, Fravor y Graves bajo juramento', text:'El 26/7/2023, el exoficial de inteligencia David Grusch testifica bajo juramento que EE.UU. posee programas de recuperación de "vehículos no humanos", junto a los pilotos Fravor (Nimitz) y Graves. El senador Schumer impulsa la UAP Disclosure Act, aprobada solo parcialmente: crea archivos UAP en NARA pero la junta de revisión es eliminada en la negociación.' },
  { year:'2024', title:'Informe histórico de AARO y nuevas audiencias', text:'AARO publica su informe histórico (Vol. 1): no halla evidencia verificable de programas de ingeniería inversa, conclusión muy contestada por congresistas y testigos. En noviembre, nueva audiencia con el periodista Michael Shellenberger y el exfuncionario Luis Elizondo bajo juramento. La oleada de drones de Nueva Jersey cierra el año mostrando los límites de la transparencia.' },
  { year:'2025', title:'El presente', text:'AARO mantiene un portal público con casos resueltos y estadísticas; los UAP Records de NARA crecen con material desclasificado; el Congreso sigue presionando con enmiendas de protección a denunciantes. La pregunta ya no es si el fenómeno existe — los propios organismos oficiales reportan cientos de casos anuales sin resolver — sino qué es.' },
  { year:'2026', title:'PURSUE — desclasificación masiva', text:'Tras una orden ejecutiva de febrero de 2026, la administración lanza el sistema PURSUE (Presidential Unsealing and Reporting System for UAP Encounters) y el portal WAR.GOV/UFO (8 de mayo), con más de 1.700 millones de visitas. En tres tandas (8 y 22 de mayo, 12 de junio) se publican documentos, imágenes y vídeos en infrarrojo de CIA, FBI, NASA y el Pentágono. El caso estrella: cinco agentes federales describen un orbe naranja "nodriza" que expulsa orbes rojos. AARO reconoce que ~40% de los casos siguen sin explicación. Pese a la escala histórica, muchos investigadores critican que faltan los expedientes más sensibles.' },
];

const GLOSSARY = [
  ['UAP', 'Unidentified Anomalous Phenomena. Término oficial actual (antes "Unidentified Aerial Phenomena"), ampliado en 2022 para incluir objetos marinos, espaciales y transmedio.'],
  ['Clasificación Hynek', 'Sistema creado por J. Allen Hynek (asesor científico de Blue Book): Luces Nocturnas, Discos Diurnos, Radar-Visual y Encuentros Cercanos de 1º, 2º y 3º tipo. El 4º tipo (abducciones) se añadió después.'],
  ['Transmedio', 'Capacidad aparente de un objeto de moverse entre aire y agua (o espacio) sin pérdida de rendimiento. Categoría clave en los casos Nimitz, Aguadilla y Omaha.'],
  ['USO', 'Unidentified Submerged Object: objeto no identificado bajo el agua o que entra/sale del mar.'],
  ['FOIA', 'Freedom of Information Act (1966/1974). Herramienta legal con la que investigadores civiles han desclasificado decenas de miles de páginas de CIA, NSA, DIA, FBI y FAA.'],
  ['Blue Book', 'Proyecto de la USAF (1952–1969): 12.618 casos investigados, 701 oficialmente "no identificados". Archivos completos digitalizados en los Archivos Nacionales de EE.UU.'],
  ['AATIP', 'Advanced Aerospace Threat Identification Program: programa del Pentágono (2007–2012) revelado por el New York Times en 2017.'],
  ['AARO', 'All-domain Anomaly Resolution Office (2022–): oficina oficial del Departamento de Defensa para resolver casos UAP en todos los dominios. Publica informes y vídeos en aaro.mil.'],
  ['NUFORC', 'National UFO Reporting Center (1974–): mayor base de datos civil del mundo, ~180.000 reportes públicos y buscables. Acepta denuncias por web y teléfono.'],
  ['MUFON', 'Mutual UFO Network (1969–): red internacional de investigadores de campo con metodología estandarizada de investigación de casos.'],
  ['GEIPAN', 'Grupo oficial francés dentro de la agencia espacial CNES (1977–). Francia es el único país occidental con investigación civil oficial continua; ~3% de sus casos quedan como "PAN D" (inexplicados con buenos datos).'],
  ['CEFAA', 'Comité de Estudios de Fenómenos Aéreos Anómalos: organismo oficial de la aviación civil chilena, pionero en Latinoamérica.'],
  ['Efecto paralaje', 'Ilusión de velocidad/altitud causada por el movimiento de la cámara: explicación probable del vídeo GoFast. Todo análisis riguroso debe descartarlo primero.'],
  ['Hipótesis prosaicas', 'Globos, drones, bengalas, Starlink, Venus, bólidos, aves con bokeh... El 90-95% de los reportes se resuelven así. El interés científico está en el residuo que sobrevive al filtrado.'],
];

const METHODOLOGY = {
  cred: [
    [5, 'Datos instrumentales múltiples (radar + visual + sensores), testigos entrenados, documentación oficial desclasificada.'],
    [4, 'Documentación oficial o múltiples testigos independientes cualificados; evidencia física o instrumental parcial.'],
    [3, 'Testigos múltiples creíbles o evidencia física analizada, pero con lagunas o explicaciones alternativas viables.'],
    [2, 'Testimonio singular o poco corroborado; caso histórico relevante pero débil probatoriamente.'],
    [1, 'Caso famoso pero desacreditado, contaminado o con explicación prosaica probable. Se incluye por su valor histórico y didáctico.'],
  ],
  notes: 'UFOlogist aplica el principio del residuo: la mayoría de reportes tienen explicación convencional, y un catálogo riguroso debe decirlo. Cada caso enlaza a sus fuentes primarias (documentos desclasificados, archivos nacionales, prensa de la época) para que verifiques por ti mismo. La credibilidad evalúa la calidad de la evidencia, no la "espectacularidad" del relato.'
};

// Shape metadata for the NUFORC mass database (order = index in data/nuforc.json)
const SHAPE_META = [
  { code:'light',     label:'Luz',         color:'#ffd166' },
  { code:'fireball',  label:'Bola de fuego', color:'#ff7b54' },
  { code:'orb',       label:'Esfera/Orbe', color:'#8ecae6' },
  { code:'triangle',  label:'Triángulo',   color:'#ef476f' },
  { code:'disk',      label:'Disco',       color:'#b388ff' },
  { code:'cigar',     label:'Cigarro/Cilindro', color:'#57cc99' },
  { code:'oval',      label:'Óvalo/Lágrima', color:'#f4a8ff' },
  { code:'geometric', label:'Geométrico',  color:'#80ed99' },
  { code:'formation', label:'Formación',   color:'#f78c6b' },
  { code:'other',     label:'Otro/Desc.',  color:'#93a1c0' },
];

// GEIPAN classification (official French CNES scale) — order = index in data/geipan.json
const GEIPAN_META = [
  { code:'A', label:'A · Identificado',        color:'#6c8b7f', desc:'Fenómeno identificado con certeza (avión, globo, Venus, dron…).' },
  { code:'B', label:'B · Prob. identificado',  color:'#8ecae6', desc:'Identificación muy probable, sin certeza total.' },
  { code:'C', label:'C · Sin datos',           color:'#ffd166', desc:'Datos insuficientes para concluir.' },
  { code:'D', label:'D · Inexplicado',         color:'#ef476f', desc:'Inexplicado pese a datos consistentes (incluye D1/D2). El residuo de mayor interés.' },
];

// Legendary hotspots (point of interest layer)
const HOTSPOTS = [
  { name:'Área 51 / Rachel, NV', lat:37.24, lng:-115.81, desc:'Base secreta de pruebas aeroespaciales (Groom Lake). Epicentro de la mitología moderna desde las afirmaciones de Bob Lazar (1989). La "Extraterrestrial Highway" (SR-375) la rodea.' },
  { name:'Rancho Skinwalker, UT', lat:40.258, lng:-109.888, desc:'Rancho de la cuenca Uinta con décadas de fenómenos reportados. Investigado por NIDS y por el programa AAWSAP del Pentágono (2008-2010); hoy objeto de la serie de History Channel.' },
  { name:'Valle de San Luis, CO', lat:37.6, lng:-105.8, desc:'Valle de Colorado con casuística continua desde los años 60, incluida la primera mutilación de ganado famosa ("Snippy", 1967). Tiene incluso una "UFO Watchtower".' },
  { name:'Hessdalen, Noruega', lat:62.8, lng:11.19, desc:'El único hotspot con monitorización científica permanente: estaciones automáticas registran luces anómalas desde 1983 (Proyecto Hessdalen, Østfold University College).' },
  { name:'Molebka ("Triángulo M"), Rusia', lat:57.65, lng:57.05, desc:'La "zona anómala" más famosa de Rusia, junto al río Sylva en los Urales. Popular desde los años 80; tiene monumento a un alienígena.' },
  { name:'Wycliffe Well, Australia', lat:-20.79, lng:134.23, desc:'Autodenominada "capital australiana de los OVNIs", en el Territorio del Norte. Avistamientos reportados de forma continua desde la 2ª Guerra Mundial.' },
  { name:'Zona del Silencio, México', lat:26.69, lng:-103.75, desc:'Desierto entre Durango, Chihuahua y Coahuila. La leyenda creció tras caer allí un misil Athena de EE.UU. en 1970. Folclore de anomalías magnéticas y avistamientos.' },
  { name:'Valle del Hudson, NY', lat:41.4, lng:-73.9, desc:'Escenario de la gran oleada de objetos triangulares de 1982-86 (5.000+ testigos) investigada por J. Allen Hynek.' },
  { name:'Triángulo de las Bermudas', lat:25.0, lng:-70.0, desc:'Más mito popular que casuística rigurosa, pero asociado al Vuelo 19 (1945) y a especulación USO. Útil como caso de estudio del folclore.' },
  { name:'Pembrokeshire ("Triángulo Galés")', lat:51.78, lng:-5.11, desc:'Oleada de 1977 ("Dyfed Triangle"): colegio de Broad Haven, hotel Haven Fort y granjas costeras. Documentado en archivos del MoD británico.' },
  { name:'Colares, Brasil', lat:-0.94, lng:-48.28, desc:'Isla amazónica de la Operação Prato (1977): el único despliegue militar oficial documentado para investigar ataques de luces a la población.' },
  { name:'Canal de Catalina / SOCAL', lat:33.3, lng:-118.5, desc:'Corredor marítimo entre San Diego y las islas del Canal: incidentes Nimitz (2004), enjambres de drones sobre destructores (2019) y casuística USO histórica.' },
  { name:'Monte Shasta, CA', lat:41.41, lng:-122.19, desc:'Montaña sagrada con folclore de luces y "ciudades intraterrenas" (mito de Lemuria/Telos). Hotspot espiritual-contactista clásico del oeste americano.' },
  { name:'Es Vedrà, Ibiza', lat:38.866, lng:1.197, desc:'Islote magnético frente a la costa suroeste de Ibiza, epicentro del folclore OVNI balear. Citado en los expedientes desclasificados del Ejército del Aire; rodeado de leyendas sobre anomalías de brújula y luces.' },
  { name:'Serra de Tramuntana / Sóller', lat:39.78, lng:2.72, desc:'La sierra del noroeste de Mallorca y, en especial, Sóller fueron el punto más activo de la casuística balear entre los años 70 y 90, con fotos integradas en los expedientes oficiales.' },
];

// Key events shown on the timeline (explain report spikes & context)
const TL_EVENTS = [
  { year:1947, label:'Arnold + Roswell: nace la era platillista' },
  { year:1952, label:'Gran oleada — radares de Washington D.C.' },
  { year:1957, label:'Sputnik + oleada de Levelland' },
  { year:1966, label:'"Gas de pantano" → Informe Condon' },
  { year:1969, label:'Cierre del Proyecto Blue Book' },
  { year:1973, label:'Oleada de 1973 (Pascagoula, Coyne)' },
  { year:1980, label:'Rendlesham + Cash-Landrum' },
  { year:1989, label:'Ola belga + Voronezh' },
  { year:1997, label:'Luces de Phoenix' },
  { year:2004, label:'Incidente Nimitz "Tic Tac"' },
  { year:2008, label:'Stephenville; pico de reportes NUFORC' },
  { year:2017, label:'NYT revela AATIP — era UAP' },
  { year:2021, label:'Informe ODNI al Congreso' },
  { year:2023, label:'Audiencia Grusch + derribos de febrero' },
  { year:2024, label:'Drones de Nueva Jersey' },
  { year:2026, label:'Desclasificación PURSUE — war.gov/ufo' },
];

// Guided expedition through essential cases (chronological)
const TOUR_IDS = [
  'kenneth-arnold-1947', 'roswell-1947', 'washington-1952', 'levelland-1957',
  'socorro-1964', 'malmstrom-1967', 'tehran-1976', 'colares-1977',
  'rendlesham-1980', 'jal1628-1986', 'belgian-f16-1990', 'ariel-1994',
  'phoenix-1997', 'nimitz-2004', 'gimbal-2015', 'lake-huron-2023', 'pursue-orbs-2023',
];

const REPORT_LINKS = [
  ['NUFORC — reportar un avistamiento', 'https://nuforc.org/file-a-report/'],
  ['MUFON — Submit a report', 'https://mufon.com/cms-report-a-ufo/'],
  ['GEIPAN (Francia) — témoignage', 'https://www.cnes-geipan.fr/'],
  ['AARO — informes oficiales y casos resueltos', 'https://www.aaro.mil/'],
  ['Archivos Blue Book (NARA)', 'https://www.archives.gov/research/military/air-force/ufos'],
  ['The Black Vault — documentos FOIA', 'https://www.theblackvault.com/'],
  ['Archivos UFO del Reino Unido (National Archives)', 'https://www.nationalarchives.gov.uk/ufos/'],
  ['Expedientes OVNI desclasificados de España', 'https://bibliotecavirtual.defensa.gob.es/BVMDefensa/expedientes-ovni'],
];
